### ISSUE TITLE
This version doesn't work in Redmine(3.4.x)

### ISSUE THREAD

**Issue by kaitaku** [HugoHasenbein/redmine_my_page_paginations#1]
Thank you for your efforts.

This version doesn't work in Redmine(3.4.x)
Please make it work.

ActionView::Template::Error (No route matches {:action=>"update", :controller=>"my_page_paginations", :id=>"", :page=>2} missing required keys: [:id]):
    38:         @issue_pages, 
    39:         query.issue_count, 
    40:         :per_page_links => true 
    41:       ) { |text, parameters, options| link_to text, update_my_page_paginations_path(query.id ? "#{query.id}" : query.name.parameterize, parameters), options } %></span>
    42:   <%- end %>
    43: <% content_for :header_tags do %>
    44: <%= auto_discovery_link_tag(:atom,
  plugins/redmine_my_page_paginations/app/views/my/patched_blocks/_issues.erb:41:in `block in _plugins_redmine_my_page_paginations_app_views_my_patched_blocks__issues_erb___2627220882970693568_70126544588560'
  lib/redmine/pagination.rb:146:in `block in pagination_links_full'
  lib/redmine/pagination.rb:186:in `block in pagination_links_each'
  lib/redmine/pagination.rb:178:in `each'
  lib/redmine/pagination.rb:178:in `pagination_links_each'
  lib/redmine/pagination.rb:144:in `pagination_links_full'
  plugins/redmine_my_page_paginations/app/views/my/patched_blocks/_issues.erb:37:in `_plugins_redmine_my_page_paginations_app_views_my_patched_blocks__issues_erb___2627220882970693568_70126544588560'
  plugins/redmine_my_page_paginations/lib/redmine_my_page_paginations/patches/my_helper_patch.rb:57:in `render_issuesreportedbyme_block'

**Comment by HugoHasenbein** [comment]
Dear Kaitaku,

are you using this plugin together with unread_issues plugin? The error lines tell me where to look fo the error, but I need some more info how the error can be reproduced.

Best regards

Stephan

**Comment by HugoHasenbein** [comment]
Dear Kaitaku,

try this version and please tell me if the error persists

Best regards

Stephan

**Comment by HugoHasenbein** [comment]
resolved
