### ISSUE TITLE
if the language change to chinese simple there will have an error opening the my page

### ISSUE THREAD

**Issue by upbeat-backbone-bose** [HugoHasenbein/redmine_my_page_paginations#3]
![image](https://user-images.githubusercontent.com/438092/71143970-5c0bd580-2257-11ea-87cf-e72852c13be2.png)

![image](https://user-images.githubusercontent.com/438092/71143810-cd975400-2256-11ea-958d-f2a5b58f6857.png)

Trace of template inclusion: app/views/my/page.html.erb

Rails.root: /var/www/html/redmine

Application Trace | Framework Trace | Full Trace
actionpack (4.2.11.1) lib/action_dispatch/journey/formatter.rb:46:in `generate'
actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:721:in `generate'
actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:752:in `generate'
actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:799:in `url_for'
actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:280:in `call'
actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:345:in `block (2 levels) in define_url_helper'
plugins/redmine_my_page_paginations/app/views/my/patched_blocks/_issues.erb:41:in `block in _plugins_redmine_my_page_paginations_app_views_my_patched_blocks__issues_erb__3587976674371565553_70272958791920'
lib/redmine/pagination.rb:146:in `block in pagination_links_full'
lib/redmine/pagination.rb:186:in `block in pagination_links_each'
lib/redmine/pagination.rb:178:in `each'
lib/redmine/pagination.rb:178:in `pagination_links_each'
lib/redmine/pagination.rb:144:in `pagination_links_full'
plugins/redmine_my_page_paginations/app/views/my/patched_blocks/_issues.erb:37:in `_plugins_redmine_my_page_paginations_app_views_my_patched_blocks__issues_erb__3587976674371565553_70272958791920'
actionview (4.2.11.1) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.11.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.11.1) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.11.1) lib/action_view/template.rb:143:in `render'
actionview (4.2.11.1) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
actionview (4.2.11.1) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
actionview (4.2.11.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.11.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.11.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.11.1) lib/action_view/renderer/partial_renderer.rb:309:in `render'
actionview (4.2.11.1) lib/action_view/renderer/renderer.rb:51:in `render_partial'
actionview (4.2.11.1) lib/action_view/renderer/renderer.rb:25:in `render'
actionview (4.2.11.1) lib/action_view/helpers/rendering_helper.rb:32:in `render'
plugins/redmine_my_page_paginations/lib/redmine_my_page_paginations/patches/my_helper_patch.rb:57:in `render_issuesreportedbyme_block'
app/helpers/my_helper.rb:64:in `render_block_content'
app/helpers/my_helper.rb:35:in `render_block'
app/helpers/my_helper.rb:27:in `block in render_blocks'
app/helpers/my_helper.rb:26:in `each'
app/helpers/my_helper.rb:26:in `render_blocks'
app/views/my/page.html.erb:13:in `block in _app_views_my_page_html_erb___2808313983304255700_70272958425260'
app/views/my/page.html.erb:11:in `each'
app/views/my/page.html.erb:11:in `_app_views_my_page_html_erb___2808313983304255700_70272958425260'
actionview (4.2.11.1) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.11.1) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.11.1) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.11.1) lib/action_view/template.rb:143:in `render'
actionview (4.2.11.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
actionview (4.2.11.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.11.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `instrument'
actionview (4.2.11.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
actionview (4.2.11.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
actionview (4.2.11.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
actionview (4.2.11.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.11.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.11.1) lib/action_view/renderer/renderer.rb:46:in `render_template'
actionview (4.2.11.1) lib/action_view/renderer/renderer.rb:27:in `render'
actionview (4.2.11.1) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.11.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.11.1) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.11.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.11.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.11.1) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.11.1) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.11.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.11.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/root/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
activesupport (4.2.11.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.11.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.11.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (4.2.11.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.2.11.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (4.2.11.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (4.2.11.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
actionpack (4.2.11.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.11.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.11.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:432:in `block in make_lambda'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:312:in `block in halting'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:497:in `block in around'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.11.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.11.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.11.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.11.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.11.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.11.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.11.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.11.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.11.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.11.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.11.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.11.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.11.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.11.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.11.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.11.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.11.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
rack (1.6.11) lib/rack/etag.rb:24:in `call'
rack (1.6.11) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.11) lib/rack/head.rb:13:in `call'
actionpack-xml_parser (1.0.2) lib/action_dispatch/xml_params_parser.rb:16:in `call'
actionpack (4.2.11.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.11.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.11) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.11) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.11.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.11.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.11.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
actionpack (4.2.11.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
activesupport (4.2.11.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.11.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.11.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.11.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.11.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.2.11.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.11.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.11.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.11.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.11.1) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.11.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.11) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.11) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.11.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.11) lib/rack/lock.rb:17:in `call'
actionpack (4.2.11.1) lib/action_dispatch/middleware/static.rb:120:in `call'
rack (1.6.11) lib/rack/content_length.rb:15:in `call'
rack (1.6.11) lib/rack/sendfile.rb:113:in `call'
railties (4.2.11.1) lib/rails/engine.rb:518:in `call'
railties (4.2.11.1) lib/rails/application.rb:165:in `call'
rack (1.6.11) lib/rack/lock.rb:17:in `call'
rack (1.6.11) lib/rack/content_length.rb:15:in `call'
rack (1.6.11) lib/rack/handler/webrick.rb:88:in `service'
/root/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
/root/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
/root/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/webrick/server.rb:314:in `block in start_thread'

**Comment by HugoHasenbein** [comment]
Dear Ray,

will redmine crash if you switch back to english? Can you list your other plugins you use?

Best regards

Stephan

**Comment by HugoHasenbein** [comment]
issue is resolved

**Comment by upbeat-backbone-bose** [comment]
> issue is resolved

thanks for you great job. LoL
